### ISSUE TITLE
Automatically add/update user meta values based on ENS text records

### ISSUE THREAD

**Issue by davisshaver** [davisshaver/wp-rainbow#11]
As a site administrator, I want to enrich WP Rainbow user accounts based on ENS text records, so that users can have automatically updated information on their WordPress user profiles.

Default user meta values in WordPress include email, website, and bio.

**Comment by mcardlej** [comment]
This could be extended to even more than the default fields available in ENS. We already have:

Email (email)
Website (url)
Biographical info (description)
Profile picture (avatar) - Need to work out how to take the NFT and convert as image
Twitter username (com.twitter)

Can then create new wordpress specific ENS TEXT records such as:
Firstname (com.wordpress.firstname)
Lastname (com.wordpress.lastname)
Nickname (com.wordpress.nickname)

Thanks
James

**Comment by davisshaver** [comment]
First version of this is out in v0.2.17! Here's an example mapping:

```
url,user_url
email,user_email
com.twitter,twitter
location,description
```

<img width="990" alt="Screen Shot 2022-09-04 at 10 27 13 AM" src="https://user-images.githubusercontent.com/1636964/188318589-b2d1890a-b8fe-4263-89c7-8eafd889892b.png">

Looking forward to feedback on this! We can incorporate any findings into #35 when we'll have a chance to revamp this admin.
