### ISSUE TITLE
Parse error when activating plugin

### ISSUE THREAD

**Issue by architek1** [davisshaver/wp-rainbow#49]
I'm having trouble activating the plugin. I'm getting this error:

`Parse error: syntax error, unexpected 'WP_Rainbow' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in ~/public_html/wp-content/plugins/rainbowkit-login-web3-integration-for-sign-in-with-ethereum/inc/class-wp-rainbow.php on line 20`

I've reinstalled the plugin multiple times. Currently running WP 6.1.1 .

**Comment by architek1** [comment]
This is the exact line:
`protected static WP_Rainbow $instance;`

**Comment by davisshaver** [comment]
Hi @architek1 – I apologize that I missed this issue! I didn't mean to leave you hanging.

Are you installing from source? Please make sure to run `composer install` in the project folder if you are installing from source. Does that fix the issue?

Also, just curious – have you tried installing from WordPress.org? I'd be curious if that works for you.

**Comment by davisshaver** [comment]
Hi @architek1 - Thanks very much for the report! I am going to open up another issue for me to confirm the PHP requirements. It's possibly that when you installed PHP 8.2 it included a dependency for the plugin that was missing in PHP 7.2. But in any event, I'm glad it's working for you now! Please let me know if any other issues come up.
